#!/usr/bin/env sh

BASE_URL="https://github.com/dimforge"
REPOS="nalgebra ncollide nphysics simba rapier salva"
for REPO in $REPOS
do
    REPO_URL=$BASE_URL/$REPO
    [ -d $REPO ] || git clone $REPO_URL
done

